### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config/snapshots'

### ISSUE THREAD

**Issue by koldogut** [jodur/snaptogif#1]
I'm facing this error when calling the service:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/snaptogif/__init__.py:59
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:17:53 (5 occurrences)
Last logged: 10:20:03

[23084904807152] [Errno 2] No such file or directory: 'config/snapshots'
[23084904807152] [Errno 2] No such file or directory: 'config/snapshots/'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/snaptogif/__init__.py", line 59, in SnapToGIF
    files=os.listdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: 'config/snapshots'
```

Folder exists and is the one used by Deepstack, also included under `allowlist_external_dirs:`. Service call parameters below:

```
sourcepath: config/snapshots
destinationpath: config/snapshots
filename: face_counter_cocina
format: gif
excludelist: face_counter_cocina_latest.jpg
begintimestamp: '27/11/2020 21:39:00'
endtimestamp: '27/11/2020 21:40:00'

```

**Comment by koldogut** [comment]
Solved ... you must ensure folders include root `/`. Maybe examples and readme shoud be updated.
